# Generated by Django 3.1.2 on 2020-10-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20201026_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminloginmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
